### ISSUE TITLE
Merge conflict between media-libs/vulkan-base-9999 and media-libs/mesa-9999-r1

### ISSUE THREAD

**Issue by Haifen** [Lucretia/vulkan-overlay#14]
Hi-
    I'm running a modified Mesa live ebuild to include (in this case airlied's RADV) Vulkan support.  While this seems (so far) fine and dandy, Mesa wants to put some minimal Vulkan headers in /usr/include/vulkan, which conflict with those installed by vulkan-base.  This may be an issue with Mesa, and it's quite possible that the "correct" fix is to have mesa-9999-r1.ebuild not install the Vulkan headers at all (chop them out of ${WORKDIR}/image, perhaps?), but I'm also not sure if the official Khronos headers advertise features that the Mesa code may not fully support.  So, instead of a direct fix, I'm more soliciting your advice as to which package should "budge" on Vulkan support, and whether a full-on eselect-style fix may be recommended.  Thank you for all of your time and work thus far :-)

        -Robin K.

**Comment by Lucretia** [comment]
Yes, I have a mesa with radv ebuild and come across this. I just took it out of vulkan-base for now. But this needs more work, I think the best thing is to not install the mesa headers and use the vulkan-base ones. ADMGPU-Pro doesn't have any that i've noticed so far.

**Comment by Lucretia** [comment]
The following `USE=-vkheaders emerge -av vulkan-base' will install the vulkan-base package without the vulkan headers, so that Mesa can install them.
