### ISSUE TITLE
SRC_URI in amdgpu-pro-dkms ebuilds

### ISSUE THREAD

**Issue by maked0n** [Lucretia/vulkan-overlay#19]
In the amdgpu-pro-dkms ebuilds the SRC_URI variable is set as 
`SRC_URI="https://www2.ati.com/drivers/beta/amdgpu-pro_${BUILD_VER}.tar.xz"`
The correct link shlould point to the amdgpu-pro**-dkms**_${BUILD_VER}.tar.xz, shouldn't it?

**Comment by Lucretia** [comment]
No, because that's the archive containing all the debs that you download from amd.
