### ISSUE TITLE
mesa with RADV

### ISSUE THREAD

**Issue by camplusplus** [Lucretia/vulkan-overlay#21]
When using video_cards_radeon(si) I can not install new mesa without conflicts (multiple llvm versions required).
Without this use flag ( just amdgpu ) mesa is software only and glxgears outputs:

```
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
```

What use flags must be used or what should be masked, reinstalled against using this overlay with gentoo portage tree?

Thanks!!

**Comment by Lucretia** [comment]
You shouldn't have any problems with the mesa ebuild, that ebuild is copied from the gentoo tree and modified to point to a modified mesa tree. There's really no need to use that now that Mesa has RADV in mainline. Change my mesa ebuild as follows:

```EGIT_REPO_URI="git://anongit.freedesktop.org/mesa/mesa"```

Remove the ```EGIT_BRANCH``` line, then rebuild the manifest with `ebuild mesa-9999.ebuild manifest`

**Comment by Lucretia** [comment]
Latest points to mainline Mesa with RADV.
