### ISSUE TITLE
Update to 16.40

### ISSUE THREAD

**Issue by corngood** [Lucretia/vulkan-overlay#22]
AMD just released 16.40.  They are now shipping it for RHEL 6.8, 7.2 and Ubuntu 16.04.

I've been using your patches for Arch and NixOS packages, and I'm going to try to do the upgrade on NixOS (with linux-4.8.3) first.  Perhaps we can use this thread to avoid duplicating work?

**Comment by corngood** [comment]
The URL format, and required referer have changed.  Also with the new hash:

```
  build = "16.40-348864";
  src = fetchurl {
    url =
    "https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-${build}.tar.xz";
    sha256 = "1c06lx07irmlpmbmgb3qcgpzj6q6rimszrbbdrgz8kqnfpcv3mjr";
    curlOpts = "--referer http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%e2%80%93Release-Notes.aspx";
  };
```

**Comment by corngood** [comment]
I did a quick rebase on the patches and got the kernel module compiling.  I haven't tested it at all though:

https://github.com/corngood/nixpkgs/tree/amdgpu-pro-16.40/pkgs/os-specific/linux/amdgpu-pro/patches

The last two patches are not from this repo, so you might want to ignore them.

**Comment by ashleysommer** [comment]
I used these patches to build the 16.40 kernel module in Ubuntu 16.04. Two of the patches don't apply cleanly, and after checking out the code I see it is because those fixes have already been updated in the source by AMD, so don't need to be patched.

Also, this driver still needs amdgpu.dal=0 boot param, else it freeze on boot.

**Comment by corngood** [comment]
I've been using that `0014-disable-dal-by-default.patch` in Arch and NixOS on the older drivers.  I'm not sure if it's broken on all devices or not, but I haven't heard any reports of it working.  You may want to do the same thing.

**Comment by Lucretia** [comment]
Thanks. I'm checking the contents of the rhel7.2 archive as well.

**Comment by corngood** [comment]
Sounds good.  I'm up and running with GL and vulkan.  The IOMMU errors I was getting at boot are gone.  A couple of vulkan bugs are fixed, so the smoke test now runs without errors.

They changed the structure of things quite a bit, so there's now a bunch of stuff in /opt/.

**Comment by Lucretia** [comment]
Good stuff, thanks.

**Comment by Hydrar** [comment]
@corngood Used your patches to update the ebuilds, see PR #26

**Comment by dr04** [comment]
How can install in gentoo Update to 16.40? : i'm add git clone https://github.com/Hydrar/vulkan-overlay to local repos update and see only 16.30.3.315407-r1 (new user) and problem install DKMS

**Comment by stobenski** [comment]
@dr04 http://i.imgur.com/iNRW2Ew.jpg

**Comment by stobenski** [comment]
@Hydrar there is problem with your [16.40.ebuild](https://github.com/Hydrar/vulkan-overlay/blob/amdgpu-16.40/x11-drivers/amdgpu-pro/amdgpu-pro-16.40.348864.ebuild#L137):
```
>>> Unpacking ./amdgpu-pro-16.40-348864/libgles2-amdgpu-pro-dev_16.40-348864_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.40.348864/work
 * ERROR: x11-drivers/amdgpu-pro-16.40.348864::hydrar failed (unpack phase):
 *   unpack: ./amdgpu-pro-16.40-348864/libgles2-amdgpu-pro-dev_16.40-348864_amd64.deb does not exist
```
I just checked _amdgpu-pro-16.40-348864.tar.xz_ and this is true, this archive does not contain libgles2-amdgpu-pro-dev_16.40-348864_amd64.deb, only libgles2-amdgpu-pro_16.40-348864_amd64.deb (without -dev).

**Comment by Hydrar** [comment]
@dr04 I got the dkms build from some other overlay, it's just in depends so people won't complain the kernel module is missing, switch to the branch amdgpu-16.40 with git checkout amdgpu-16.40 to find the proper ebuilds

**Comment by NukeMania** [comment]
16.50 released and all GCN cards supported http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx

**Comment by 9Yg1rxeSeha90ZU1** [comment]
has 16.50 been patched to build with dkms yet? havent got it to work yet either

**Comment by Lucretia** [comment]
I'm going to work on 16.50 tomorrow.

**Comment by corngood** [comment]
16.60 is out:
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx

For 16.50 the patches I needed on nixos (up to linux-4.9 I believe) are here: https://github.com/corngood/nixpkgs/tree/amdgpu-pro-update/pkgs/os-specific/linux/amdgpu-pro/patches

I'll try to coordinate with you if I get around to working on 16.60.

**Comment by Lucretia** [comment]
I'm going to skip 50 and just go straight to 60 as 50 apparently had issues.

**Comment by corngood** [comment]
I definitely had stability problem with it on my 290, but I got good reports from people on Polaris, so I shipped it.  Hopefully 60 is better.

I also didn't find serious problems using `amdgpu.dal=1`, so I'll probably drop the patch that's disabling it.
