### ISSUE TITLE
Duplicate patch files

### ISSUE THREAD

**Issue by ashleysommer** [Lucretia/vulkan-overlay#23]
In the folder of 16.30.3-315407 source patches, the files 0001-Fix-bo-priv_flags and 0014-Fix-bo-priv_flags are both the same patch. Attempting to apply 0014 after applying 0001 will throw a `patch` command warning and ask if you want to roll back the patch.

**Comment by Lucretia** [comment]
Hmm, don't know how that got in there like that.,

**Comment by Lucretia** [comment]
The file `0001-Fix-bo-priv_flags-for-4.8.0.patch` shouldn't be there, that's from a previous patchset. The ebuild's don't even apply that patch. I'll delete it though.
