### ISSUE TITLE
Validation layer libraries not found.

### ISSUE THREAD

**Issue by mleise** [Lucretia/vulkan-overlay#24]
I found what breaks validation for me:
LDPATH="/usr/$(get_libdir)/vulkan;"
The semicolon ends up in ld.so.conf and ld can't use the path, it seems. If I remove the semicolon it works. Otherwise it works great for Intel GPUs. Thanks for the work you put into this overlay.

**Comment by Lucretia** [comment]
Yeah, that probably should be a colon.

**Comment by Lucretia** [comment]
Pushed.
