### ISSUE TITLE
Fetch Failed mesa-9999

### ISSUE THREAD

**Issue by aries2747** [Lucretia/vulkan-overlay#25]
When i try to install mesa-9999 the following error occure:

` * Package:    media-libs/mesa-9999
 * Repository: vulkan
 * USE:        abi_x86_32 abi_x86_64 amd64 classic d3d9 dri3 egl elibc_glibc gallium gbm gles2 kernel_linux nptl openmax osmesa pic udev userland_GNU vaapi vdpau wayland xa xvmc
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
Initialized empty Git repository in /usr/portage/distfiles/git3-src/Lucretia_mesa-amdgpu.git/
 * Fetching https://github.com/Lucretia/mesa-amdgpu.git ...
git fetch https://github.com/Lucretia/mesa-amdgpu.git +refs/heads/amdgpu/radv-new:refs/heads/amdgpu/radv-new
fatal: Couldn't find remote ref refs/heads/amdgpu/radv-new
 * ERROR: media-libs/mesa-9999::vulkan failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_unpack
 *   environment, line 5121:  Called git-r3_src_unpack
 *   environment, line 2951:  Called git-r3_src_fetch
 *   environment, line 2945:  Called git-r3_fetch
 *   environment, line 2867:  Called die
 * The specific snippet of code:
 *       [[ -n ${success} ]] || die "Unable to fetch from any of EGIT_REPO_URI";
 * 
 * If you need support, post the output of `emerge --info '=media-libs/mesa-9999::vulkan'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/mesa-9999::vulkan'`.
 * The complete build log is located at '/var/tmp/portage/media-libs/mesa-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-libs/mesa-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-libs/mesa-9999/work'
 * S: ['/var/tmp/portage/media-libs/mesa-9999/work/mesa-9999'`

**Comment by Lucretia** [comment]
See #21 to use the official mainline
