### ISSUE TITLE
driver 16.50 requires patch to dce_v6_0.c

### ISSUE THREAD

**Issue by 9Yg1rxeSeha90ZU1** [Lucretia/vulkan-overlay#27]
dce_v6_0.c

var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/dce_v6_0.c:1975:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .gamma_set = dce_v6_0_crtc_gamma_set,
               ^
/var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/dce_v6_0.c:1975:15: note: (near initialization for ‘dce_v6_0_crtc_funcs.gamma_set’)

**Comment by 9Yg1rxeSeha90ZU1** [comment]
got past that by disabling v6 build in Makefile, but now another error.

/var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/../backport/kcl_drm.c: In function ‘_kcl_drm_atomic_get_existing_plane_state’:
/var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/../backport/kcl_drm.c:181:17: error: ‘struct drm_atomic_state’ has no member named ‘plane_states’
     return state->plane_states[drm_plane_index(plane)];
                 ^
/var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/../backport/kcl_drm.c:182:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/usr/src/linux-headers-4.8.0-2-common/scripts/Makefile.build:294: recipe for target '/var/lib/dkms/amdgpu-pro/16.50-362463/build/amd/amdgpu/../backport/kcl_drm.o' failed

**Comment by 9Yg1rxeSeha90ZU1** [comment]
well a few more hacks and got something compiled, but removed a bunch of things no idea if it will work or not really

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:

Building module:
cleaning build area...
make -j8 KERNELRELEASE=4.8.0-2-amd64 -C /lib/modules/4.8.0-2-amd64/build M=/var/lib/dkms/amdgpu-pro/16.50-362463/build.........
cleaning build area...

DKMS: build completed.
Forcing installation of amdgpu-pro

amdgpu.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/4.8.0-2-amd64/updates/dkms/

depmod...

Backing up initrd.img-4.8.0-2-amd64 to /boot/initrd.img-4.8.0-2-amd64.old-dkms
Making new initrd.img-4.8.0-2-amd64
(If next boot fails, revert to initrd.img-4.8.0-2-amd64.old-dkms image)
update-initramfs.....

DKMS: install completed.

**Comment by jason-oliveira** [comment]
What were those hacks? I'm following your breadcrumbs.

**Comment by Lucretia** [comment]
Can you add your patch here and I'll take a look?

**Comment by 9Yg1rxeSeha90ZU1** [comment]
I already nuked it and returned this video card because the support and bugs were showstopping on Linux, especially in the 4.9 kernel. So no I don't have the patches any longer unfortunately and the driver was very buggy regardless, and still not quite stable in the older kernels either. If you ask me, Nvidia is much better and amdgpu-pro is not worth the effort and waste of time.

**Comment by jason-oliveira** [comment]
Close issue, as no work was done, no patch provided, and issue is now just wasting space.
