### ISSUE TITLE
emerge fails with use flag vdpau disabled

### ISSUE THREAD

**Issue by paulc1974** [Lucretia/vulkan-overlay#32]
When x11-drivers/amdgpu-pro is emerged with use flag -vdpau.    The emerge fails. 

* Package:    x11-drivers/amdgpu-pro-16.60.379184
* Repository: vulkan
* USE:        abi_x86_64 amd64 elibc_glibc kernel_linux opengl userland_GNU vulkan
* FEATURES:   preserve-libs sandbox userpriv usersandbox
 Unpacking source...
 Unpacking amdgpu-pro-16.60-379184.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking vulkan-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/vulkan-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgl1-amdgpu-pro-appprofiles_16.60-379184_all.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgl1-amdgpu-pro-appprofiles_16.60-379184_all.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgl1-amdgpu-pro-dri_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgl1-amdgpu-pro-dri_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgl1-amdgpu-pro-ext_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgl1-amdgpu-pro-ext_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgl1-amdgpu-pro-glx_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgl1-amdgpu-pro-glx_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgbm1-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgbm1-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libgbm1-amdgpu-pro-base_16.60-379184_all.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libgbm1-amdgpu-pro-base_16.60-379184_all.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking libegl1-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/libegl1-amdgpu-pro_16.60-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking xserver-xorg-video-amdgpu-pro_1.2.99-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/xserver-xorg-video-amdgpu-pro_1.2.99-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking ./amdgpu-pro-16.60-379184/xserver-xorg-video-modesetting-amdgpu-pro_1.18.3-379184_amd64.deb to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Unpacking data.tar.xz to /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Source unpacked in /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work
 Preparing source in /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work ...
 Source prepared.
 Configuring source in /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work ...
 Source configured.
 Compiling source in /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/work ...
 Source compiled.
 Test phase [not enabled]: x11-drivers/amdgpu-pro-16.60.379184

 Install amdgpu-pro-16.60.379184 into /var/tmp/portage/x11-drivers/amdgpu-pro-16.60.379184/image/ category x11-drivers
!!! doexe: opt/amdgpu-pro/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so does not exist
 * ERROR: x11-drivers/amdgpu-pro-16.60.379184::vulkan failed (install phase):
 *   doexe failed
 *

**Comment by Lucretia** [comment]
Fixed with amdgpu-pro-16.60.379184-r1.ebuild
