### ISSUE TITLE
Cannot seem to get repo to work

### ISSUE THREAD

**Issue by ballsystemlord** [Lucretia/vulkan-overlay#34]
Hello,
equery does not list any of the repos ebuilds. I followed your instructions in the readme.
1. Created dir /etc/portage/repose.conf
2. Created file local.conf and copied contents out of readme.
3. Ran emerge --sync, it complained that the vulkan dir did not exist.
4. Copied tree vulkan to /usr/local/overlays/
5. Made certain that everything was world readable.
6. Resync'ed.
If there is something I missed out on please let me know.

**Comment by Lucretia** [comment]
1. It's ```/etc/portage/repos.conf/local.conf```
3. You didn't git pull vulkan from git to ```/usr/local/overlays/```

**Comment by Lucretia** [comment]
Try that.

Opps, didn't mean to close this.

**Comment by ballsystemlord** [comment]
Marvellous, thanks!
(typos are killers!)
