### ISSUE TITLE
media-libs/mesa-17.0.x pulls in >=libdrm-2.4.74 overlay mesa-9999 pulls in >=libdrm-2.4.67

### ISSUE THREAD

**Issue by ballsystemlord** [Lucretia/vulkan-overlay#39]
I'm filing this in both places since I can't tell who's ebuild is incorrect.
Either the portage mesa-17.0.x has too large a requirement or the overlay's ebuild pulls in too old a version, or something else...
See also:
https://bugs.gentoo.org/show_bug.cgi?id=614382

**Comment by Lucretia** [comment]
I explain this in the README.md.

**Comment by Lucretia** [comment]
Pile on here https://www.reddit.com/r/linux_gaming/comments/63qn4b/comment/dfx0j2e?st=J16OZX5E&sh=800388f2

**Comment by ballsystemlord** [comment]
On Sat, 01 Apr 2017 23:19:07 -0700
"Luke A. Guest" <notifications@github.com> wrote:

> I explain this in the README.md.
> 
I've reread the README.

My point is that the 9999 ebuild should either clone/pull mesa version
12.9999 or that the ebuild should depend on a newer libdrm like it's
Gentoo counterparts.

Thanks,
David

**Comment by Lucretia** [comment]
If AMD released the source it's using for libdrm, then yes, but in this case, no it shouldn't. They're libdrm is so behind it's unusable now. There are missing ioctls in libdrm that AMD hasn't upstreamed yet and I can't see when they'll actually bother.
