### ISSUE TITLE
vulkan-base demos don't run

### ISSUE THREAD

**Issue by Lucretia** [Lucretia/vulkan-overlay#4]
Each crash. I think they're having trouble trying to find the layers, but I'm not sure as yet.

**Comment by mlauss** [comment]
Oh they do work, you need install a few resource files along with them (shaders, mainly)

**Comment by Lucretia** [comment]
I install them in their demo dir:

$ ls /usr/share/vulkan/demos/cube/
cube  cube.c  cube.frag  cube-frag.spv  cube.vert  cube-vert.spv

ls /usr/share/vulkan/demos/tri/
tri  tri-frag.spv  tri-vert.spv

and I think the smoketest compiles them into a header, so there's nothing for that.

All fail.

**Comment by Lucretia** [comment]
The cube demo fails on line 884:

    err = demo->fpCreateSwapchainKHR(demo->device, &swapchain, NULL,
                                     &demo->swapchain);
    assert(!err);


I've just tried to run Dota 2 with the -vulkan switch and it fails complaining of: "CreateSwapChain(); Call to vkCreateSwapchainWSI returned an error."

**Comment by mlauss** [comment]
You're using the AMD driver, right?  I've no problems with the nvidia blob, it runs all 3 demos without a hitch.

**Comment by Lucretia** [comment]
Got it going. Needed DRI3 enabled. DRI2 won't work.
