### ISSUE TITLE
Splitbrained forks

### ISSUE THREAD

**Issue by cloudkitsch** [Lucretia/vulkan-overlay#43]
Dude I'm really sorry, today I revived farmboy0's ebuilds as well, I have not had a chance to look at yours yet. I was successful: https://github.com/farmboy0/portage-overlay/issues/5

And I even moved on to building some regression tests around dkms for which I found only the 4.4 branches of aufs sources were able to successfully build: 

https://gist.github.com/cloudkitsch/f30161c0728d9f44817bfc24d90056f2

The way I finally came across your repo was by that 0x missing value which I suspected was the problem but thought I'd Google it since the error was caused by dkms itself. I feel kinda bad now, at any rate and foe what it's worth I feel like I understand the driver a lot better although I still need to test everything and see if I missed anything in your ebuilds, but maybe we could work together from here on out maintaining one branch? 

I've sort of taken an approach that I think eventually will help build some CI around amdgpu-pro so there's more public visibility for it's status. Any thoughts / interested? I'll take a look at your ebuilds tomorrow and try to get it to work. Kinda excited to get back to my favorite OS as a primary, I've been running Windows in kvm/qemu with vfio for a long time but Imy pretty tired of it.

**Comment by Lucretia** [comment]
I really don't know how you could've missed this, I posted this on reddit, it's linked from Gentoo, it's not hard to find.
